name: Publish JAR to GitHub Packages

on:
  release:
    types: [published]

permissions:
  contents: write
  packages: write

jobs:
  download-assets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get latest release info
        id: get_release_info
        run: |
          response=$(curl \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/releases/latest"
          )
          echo "::set-output name=response::$response"
      - name: Download assets
        run: |
          release_info=$(echo "${{ steps.get_release_info.outputs.response }}" | jq -r .)
          assets=$(echo "$release_info" | jq -r '.assets| [.name, .browser_download_url] | @tsv')

          echo "$assets" | while IFS=$'\t' read -r name url; do
            echo "Downloading $name from $url"
            curl -Lo "$name" "$url"
          done
      - name: List downloaded files
        run: ls -l